# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  username: root
<<<<<<< HEAD
  password: root
=======
  password: dinemedia
>>>>>>> 321e68c816ece187d05928356d5c996bec39ef2d
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: work-play_development